version: '3.8'

services:
  swagger-cliente:
    image: swaggerapi/swagger-ui
    container_name: swagger-cliente
    ports:
      - "8081:8080"  # Expose port 8081 for Microservicio-Cliente
    environment:
      SWAGGER_JSON: /app/api-cliente.yaml
    volumes:
      - ./Microservicio-Cliente:/app

  swagger-movimientos:
    image: swaggerapi/swagger-ui
    container_name: swagger-movimientos
    ports:
      - "8082:8080"  # Expose port 8082 for Microservicio-Movimientos
    environment:
      SWAGGER_JSON: /app/api-movimientos.yaml
    volumes:
      - ./Microservicio-Movimientos:/app

  swagger-orquestador:
    image: swaggerapi/swagger-ui
    container_name: swagger-orquestador
    ports:
      - "8083:8080"  # Expose port 8083 for Microservicio-Orquestador
    environment:
      SWAGGER_JSON: /app/api-orquestador.yaml
    volumes:
      - ./Microservicio-Orquestador:/app

  swagger-promociones:
    image: swaggerapi/swagger-ui
    container_name: swagger-promociones
    ports:
      - "8084:8080"  # Expose port 8084 for Microservicio-Promociones
    environment:
      SWAGGER_JSON: /app/api-promociones.yaml
    volumes:
      - ./Microservicio-Promociones:/app


  microservicio-orquestador:
    build: ./Microservicio-Orquestador
    container_name: mo_c
    ports:
      - "${MO_PORT}:8001"
    networks:
      - microservicios

  microservicio-cliente:
    build: ./Microservicio-Cliente/MicroservicioCliente
    container_name: mc_c
    ports:
      - "${MC_PORT}:8080"
    networks:
      - microservicios

  microservicio-movimientos:
    build: ./Microservicio-Movimientos
    container_name: mm_c
    ports:
      - "${MM_PORT}:8000"
    environment:
      DB_USER: ${MM_DB_USER}
      DB_PASSWORD: ${MM_DB_PASSWORD}
      DB_HOST: ${MM_DB_HOST}
      DB_PORT: ${MM_DB_PORT}
      DB_NAME: ${MM_DB_NAME}
    networks:
      - microservicios

  microservicio-promociones:
    build: ./Microservicio-Promociones
    container_name: mp_c
    ports:
      - "${MP_PORT}:8002"
    networks:
      - microservicios

networks:
  microservicios: